/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'tertiary-fixed-dim': '#c6c7c2',
        'on-secondary': '#ffffff',
        'surface-container': '#edeeed',
        'on-error-container': '#93000a',
        'tertiary-container': '#454744',
        'primary-container': '#2e4d32',
        'on-primary-fixed': '#02210a',
        'secondary-container': '#fdddb9',
        'surface-variant': '#e1e3e2',
        'on-tertiary-container': '#b4b5b0',
        'error-container': '#ffdad6',
        'on-primary-fixed-variant': '#2f4e33',
        'on-surface-variant': '#424841',
        'surface-container-lowest': '#ffffff',
        'primary': '#17361d',
        'inverse-primary': '#acd0ac',
        'on-secondary-container': '#786044',
        'on-secondary-fixed': '#281803',
        'tertiary': '#2f312e',
        'tertiary-fixed': '#e3e3de',
        'on-tertiary-fixed-variant': '#454744',
        'error': '#ba1a1a',
        'on-primary': '#ffffff',
        'surface-container-low': '#f3f4f3',
        'primary-fixed': '#c7ecc7',
        'primary-fixed-dim': '#acd0ac',
        'on-primary-container': '#9abd9b',
        'on-surface': '#191c1c',
        'on-background': '#191c1c',
        'surface': '#f8faf9',
        'secondary-fixed': '#fdddb9',
        'surface-container-high': '#e7e8e7',
        'inverse-on-surface': '#f0f1f0',
        'inverse-surface': '#2e3131',
        'secondary-fixed-dim': '#e0c29f',
        'secondary': '#715a3e',
        'on-tertiary-fixed': '#1a1c19',
        'background': '#f8faf9',
        'on-tertiary': '#ffffff',
        'surface-bright': '#f8faf9',
        'outline-variant': '#c2c8bf',
        'surface-dim': '#d9dad9',
        'surface-tint': '#466649',
        'surface-container-highest': '#e1e3e2',
        'on-error': '#ffffff',
        'on-secondary-fixed-variant': '#584329',
        'outline': '#737971',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Work Sans', 'sans-serif'],
        label: ['Work Sans', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
    },
  },
  plugins: [require('@tailwindcss/forms')],
};